### ISSUE TITLE
Syntax error when initializing a uniform to a default value

### ISSUE THREAD

**Issue by ralucado** [graphitemaster/glsl-parser#11]
The [standard GLSL initalizer syntax](https://www.khronos.org/opengl/wiki/Uniform_(GLSL)) supports uniform default value initialization on declariation like so:
`uniform vec3 initialUniform = vec3(1.0, 0.0, 0.0);`
However this parser throws a "syntax error" when this is attempted.

**Comment by graphitemaster** [comment]
Yes this is a legitimate bug.

**Comment by ralucado** [comment]
Awesome!
